# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices-app
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM=  # base64 encoded 'postgres'
  DB_USER: cG9zdGdyZXM=      # base64 encoded 'postgres'